#ifndef SPARSEWAVE_DIALECT_SPARSEWAVE_IR_SPARSEWAVEDIALECT_H
#define SPARSEWAVE_DIALECT_SPARSEWAVE_IR_SPARSEWAVEDIALECT_H

#include "mlir/IR/Dialect.h"

#include "sparsewave/Dialect/SparseWave/IR/SparseWaveOpsDialect.h.inc"

#endif // SPARSEWAVE_DIALECT_SPARSEWAVE_IR_SPARSEWAVEDIALECT_H
